server:
  port: 8080
  servlet:
    context-path: /springboot
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.108:3306/test
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # schema:

  #      - classpath:department.sql
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:com/ergou/springbootmybatis/mapper/**/*Mapper.xml
#  config-location:
#  configuration:
#    map-underscore-to-camel-case: true

#logging.config=classpath:log/logback-spring.xml
#ogging.path=D:/nmyslog/nmys

#  spring.mvc.view.prefix=/WEB-INF/
#  spring.mvc.view.suffix=.jsp
logging:
  config: classpath:log/logback-spring.xml
  path: E:/log/logback